server:
  port: ${PORT:8085}   # Render inyecta $PORT

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_BASE_URL}
          predicates:
            - Path=/auth/**,/actuator/health
          filters:
            - StripPrefix=1
  webflux:
    cors:
      mappings:
        "[/**]":
          allowedOrigins: "*"
          allowedMethods: "*"

app:
  jwt:
    secret: ${APP_JWT_SECRET}